# Generated by Django 4.0.4 on 2022-05-09 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('exercise_name', models.TextField()),
                ('exercise_description', models.TextField()),
                ('exercise_category', models.CharField(choices=[('single_pose', 'single_pose'), ('multiple_pose', 'multiple_pose')], max_length=50)),
                ('exercise_type', models.CharField(choices=[('full_body', 'full_body'), ('upper_body', 'upper_body'), ('lower_body', 'lower_body')], max_length=50)),
                ('duration', models.IntegerField(null=True)),
                ('reps', models.IntegerField(null=True)),
                ('video', models.FileField(upload_to='video/')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pose_id', models.TextField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.exercise')),
            ],
        ),
    ]
