# Generated by Django 4.0.4 on 2022-05-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprogress',
            name='points_earned',
            field=models.FloatField(),
        ),
    ]
